version: '3.4'
 
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: MyDooDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 645736
      PGDATA: /Library/PostgreSQL/15/data
  web_api:
    build:
      context: .
      dockerfile: MyDoo/Dockerfile
    ports:
      - "5001:80"
  # telegram_bot:
  #   build:
  #     context: .
  #     dockerfile: MyDooBot2.0/MyDooBot2.0/Dockerfile