version: '3.4'
 
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: MyDooDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 645736
      PGDATA: /Library/PostgreSQL/15/data
    ports:
      - "54321:5432"
  web_api:
    build:
      context: .
      dockerfile: MyDoo/Dockerfile
    ports:
      - "5001:80"
  telegram_bot:
    build:
      context: .
      dockerfile: MyBot/Dockerfile
  rabbitmq3:
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=nshkabura
      - RABBITMQ_DEFAULT_PASS=1qazXSW@
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
  ui:
    build:
      context: .
      dockerfile: MyDooUI/Dockerfile
    ports:
      - "80:3000"